# -*- coding: utf-8 -*-
"""tgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2eUBqjRKqo9hPGPdFm8P4p5O1Y5zPuj
"""

import pandas as pd
import numpy as np
import scipy

questions=pd.read_csv("/content/drive/MyDrive/IAI/Questions.csv",encoding="latin1")
answers=pd.read_csv("/content/drive/MyDrive/IAI/Answers.csv",encoding="latin1")
questions.head()

print(answers.columns)

questions=questions[["Id","Title","Body","Score","CreationDate"]]
answers=answers[["Id","ParentId","Score","Body","CreationDate"]]

print(questions.isnull().sum())
print(answers.isnull().sum())
print(questions.count())

questions=questions.sort_values(by="Score",ascending=False)
questions=questions.head(500)
top_ids=questions['Id']
answers=answers[answers['ParentId'].isin(top_ids)]

questions.isnull().sum()
answers.isnull().sum()

print(questions)
print(answers)

answers.dtypes
answers["ParentId"].unique()
answers["acount"]=answers.groupby("ParentId")["Id"].transform("count")
print(answers["acount"])

from datetime import datetime
merged = answers.merge(
    questions[["Id", "CreationDate"]],
    left_on="ParentId",
    right_on="Id",
    suffixes=("_ans", "_ques")
)

merged["time"] = pd.to_datetime(merged["CreationDate_ans"]) - pd.to_datetime(merged["CreationDate_ques"])
merged.set_index("Id_ans",inplace=True)
time=merged["time"]
time

import matplotlib.pyplot as plt
import seaborn as sns
fig=plt.figure(figsize=(10,12))
plt.plot("Score","CreationDate",data=answers)
plt.xlabel("score")
plt.ylabel("time")
plt.title("Score vs time")
plt.show()

"""lower time indeed gets higher scores as we can see that as creationdate increases the score gets saturated with distribution's mean possibly lying close to lower half"""

grouped=answers.groupby("ParentId").agg({"Score":"mean","Id":"count"})
grouped.columns=["avgscore","acount"]
grouped.plot.scatter("avgscore","acount")
plt.show()

"""there are a few exceptions but the overall trend looks to following a inverse proportionality curve where as acount decreases avgscore increases and the hypothesis seems to be true but that is exactly what we are measuring acount indirectly via influx (threshold based) , so if i remove the threshold and just include influx each answer will have a influx based on its acount and the more the competition the less will be score so we indeed to penalize the value but not threshold it perhaps as without the threshold it automatically adjusts based on competition otherwise it might get 0 value"""

#start applying text based pre processing on questions[['Title','Body']] and answers['Body']
import re
from nltk.corpus import stopwords
import string
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from textblob import TextBlob
punct=string.punctuation
def remove_punctuations(text):
  return text.translate(str.maketrans("","",punct))
questions[["Title","Body"]]=questions[["Title","Body"]].apply(lambda x:x.str.lower())
answers["Body"]=answers["Body"].apply(lambda x:x.lower())
questions["Title"]=questions["Title"].apply(remove_punctuations)
questions["Body"]=questions["Body"].apply(remove_punctuations)
answers["Body"]=answers["Body"].apply(remove_punctuations)

print(questions["Body"])

import nltk
nltk.download("stopwords")
nltk.download("punkt_tab")
nltk.download("wordnet")

from nltk.corpus import stopwords
stopwords=set(stopwords.words("english"))
def remove_stopwords(text):
  new=[]
  for word in text.split():
    if word in stopwords:
      new.append("")
    else:
      new.append(word)
  x=new[:]
  new.clear()
  return " ".join(x)
questions["Title"]=questions["Title"].apply(remove_stopwords)
questions["Body"]=questions["Body"].apply(remove_stopwords)
answers["Body"]=answers["Body"].apply(remove_stopwords)

import nltk
nltk.download('averaged_perceptron_tagger_eng')

from nltk.corpus import wordnet
from nltk import pos_tag

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    return wordnet.NOUN

lem = WordNetLemmatizer()
def lemma(text):
    words = word_tokenize(text)
    pos_tags = pos_tag(words)

    return [
        lem.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in pos_tags
    ]
questions["Title"]=questions["Title"].apply(lemma)
questions["Body"]=questions["Body"].apply(lemma)
answers["Body"]=answers["Body"].apply(lemma)

questions[["Title","Body"]]

import numpy as np
import math

class Docs:
    def __init__(self, query, answers):
        self.query = set(query)
        self.answers = {k: set(v) for k, v in answers.items()}

        self.graph = {}
        self.I = {}
        self.R = {}
        self.P = {}

        self.alpha = 0.1
        self.lam = 0

    # Step 1: Compute P(Di | q)
    def compute_P(self):
        for key, value in self.answers.items():
            if len(self.query) == 0:
                self.P[key] = 0
            else:
                self.P[key] = len(value & self.query) / len(self.query)

    # Step 2: Compute Iw(D)
    def compute_I(self):
        all_sims = []

        # first pass → compute similarities
        pairwise_sims = {}

        for key, value in self.answers.items():
            pairwise_sims[key] = []

            for k, v in self.answers.items():
                if k != key:
                    if len(value | v) == 0:
                        sim = 0
                    else:
                        sim = len(value & v) / len(v)

                    pairwise_sims[key].append(sim)
                    all_sims.append(sim)



        # second pass → apply threshold
        for key, sims in pairwise_sims.items():
            wts = [sim for sim in sims]
            self.graph[key] = wts
            self.I[key] = sum(wts)

    # Step 3: Compute final rank
    def compute_R(self):
        # dynamic lambda
        k = len(self.answers)
        self.lam = 1 / (1 + math.log(k + 1))

        for key in self.answers:
            t_seconds=time[key].total_seconds()
            self.R[key] = self.P[key] * (1 + self.lam * self.I[key]) * 1/float(t_seconds) if t_seconds>0 else 0
    # Step 4: Full pipeline
    def solve(self):
        self.compute_P()
        self.compute_I()

        # normalize I
        max_I = max(self.I.values()) if self.I else 1
        for key in self.I:
            self.I[key] = self.I[key] / max_I if max_I > 0 else 0

        self.compute_R()

    # Step 5: Ranking
    def rank(self, top_k=5):
        return sorted(self.R.items(), key=lambda x: x[1], reverse=True)[:top_k]

#now the next step would be to create an object for each question and answer pair and compute the rank
final={}
for i,query in questions.iterrows():
  query_tokens=query["Title"]+query["Body"]
  answers_dict={}
  ans=answers[answers["ParentId"]==query["Id"]]
  answers_dict={row["Id"]:row["Body"]
               for i,row in ans.iterrows()}
  q=Docs(query_tokens,answers_dict)
  q.solve()
  final[query['Id']]=q.rank()

import matplotlib.pyplot as plt
import seaborn as sns
correct=0
total=0
for i,query in questions.iterrows():
  if query["Id"] not in final:
    continue
  ans=answers[answers["ParentId"]==query["Id"]]
  best_score=ans.loc[ans["Score"].idxmax()]["Id"]
  final_score=final[query["Id"]][0][0]
  if best_score==final_score:
    correct+=1
  total+=1
print(correct/total)